"""Create CV schema

Revision ID: 5665d3759eee
Revises: bca9774733ab
Create Date: 2025-08-11 22:22:36.702708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5665d3759eee'
down_revision: Union[str, Sequence[str], None] = 'bca9774733ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cvskill',
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('cv_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cv_id'], ['cv.id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['skillitem.id'], ),
    sa.PrimaryKeyConstraint('skill_id', 'cv_id')
    )
    op.drop_column('cv', 'education')
    op.drop_column('cv', 'experience')
    op.drop_column('cv', 'skills')
    op.add_column('educationitem', sa.Column('cv_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_educationitem_cv_id'), 'educationitem', ['cv_id'], unique=False)
    op.create_foreign_key(None, 'educationitem', 'cv', ['cv_id'], ['id'])
    op.add_column('experienceitem', sa.Column('start', sa.Date(), nullable=False))
    op.add_column('experienceitem', sa.Column('end', sa.Date(), nullable=True))
    op.add_column('experienceitem', sa.Column('cv_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_experienceitem_cv_id'), 'experienceitem', ['cv_id'], unique=False)
    op.create_foreign_key(None, 'experienceitem', 'cv', ['cv_id'], ['id'])
    op.drop_column('experienceitem', 'start_year')
    op.drop_column('experienceitem', 'end_year')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('experienceitem', sa.Column('end_year', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('experienceitem', sa.Column('start_year', sa.DATE(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'experienceitem', type_='foreignkey')
    op.drop_index(op.f('ix_experienceitem_cv_id'), table_name='experienceitem')
    op.drop_column('experienceitem', 'cv_id')
    op.drop_column('experienceitem', 'end')
    op.drop_column('experienceitem', 'start')
    op.drop_constraint(None, 'educationitem', type_='foreignkey')
    op.drop_index(op.f('ix_educationitem_cv_id'), table_name='educationitem')
    op.drop_column('educationitem', 'cv_id')
    op.add_column('cv', sa.Column('skills', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('cv', sa.Column('experience', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('cv', sa.Column('education', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_table('cvskill')
    # ### end Alembic commands ###
