"""extend skill fields

Revision ID: bca9774733ab
Revises: 28bcfe78d3bf
Create Date: 2025-08-11 20:41:11.027979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

skillcategory_enum = postgresql.ENUM(
    "PROGRAMMING", "NETWORKING", "DATA_SCIENCE", "ARCHITECTURE", "OTHER",
    name="skillcategory",
    create_type=False,  # we will create/drop manually
)

# revision identifiers, used by Alembic.
revision: str = 'bca9774733ab'
down_revision: Union[str, Sequence[str], None] = '28bcfe78d3bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    skillcategory_enum.create(op.get_bind(), checkfirst=True)
    op.add_column(
        "skillitem",
        sa.Column("category", skillcategory_enum, nullable=True),
    )
    op.add_column('skillitem', sa.Column('years_experience', sa.Integer(), nullable=True))
    op.add_column('skillitem', sa.Column('last_used', sa.Date(), nullable=True))
    op.add_column('skillitem', sa.Column('tools', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False))
    op.add_column('skillitem', sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('skillitem', 'description')
    op.drop_column('skillitem', 'tools')
    op.drop_column('skillitem', 'last_used')
    op.drop_column('skillitem', 'years_experience')
    op.drop_column('skillitem', 'category')
    skillcategory_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
