name: CI

on:
  push:
    branches: [develop, main]
  pull_request:
    branches: [develop, main]

jobs:
  frontend:
    name: Frontend Checks
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install legazy deps
        run: npm install --no-audit --save --legacy-peer-deps @testing-library/jest-dom@^5.16.1 @testing-library/react@^13.0.0 @testing-library/user-event@^13.5.0 web-vitals@^2.1.4 workbox-background-sync@^6.4.2 workbox-broadcast-update@^6.4.2 workbox-cacheable-response@^6.4.2 workbox-core@^6.4.2 workbox-expiration@^6.4.2 workbox-google-analytics@^6.4.2 workbox-navigation-preload@^6.4.2 workbox-precaching@^6.4.2 workbox-range-requests@^6.4.2 workbox-routing@^6.4.2 workbox-strategies@^6.4.2 workbox-streams@^6.4.2

      - name: Install Dependencies
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm test

  backend:
    name: Backend Checks
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8 pytest

      - name: Lint
        run: flake8 app

      - name: Test
        run: pytest